[package]
name = "xenolith-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Import-free Windows x64 packer runtime"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }
hkdf = { version = "0.12", default-features = false }
chacha20 = { version = "0.9", default-features = false }
poly1305 = { version = "0.8", default-features = false }
cipher = { version = "0.4", default-features = false }
universal-hash = { version = "0.5", default-features = false }
